Repository ynput/ayon-usd, pull requests merged in 2024-09, with the labels that each got.

#35 Fix typos/grammar
  Docs/Ayon_Docs/Admin_Docs.md
  README.md
  server/settings/main.py
Labels: enhancement

#33 Refactor Settings and fix launch environment
  Docs/Ayon_Docs/Admin_Docs.md
  client/ayon_usd/__init__.py
  client/ayon_usd/addon.py
  client/ayon_usd/config.py
  client/ayon_usd/hooks/__init__.py
  client/ayon_usd/hooks/pre_resolver_init.py
  client/ayon_usd/utils.py
  client/ayon_usd/version.py
  create_package.py
  server/settings/main.py
Labels: bug, enhancement

#41 Create pinning file during publishing
  client/ayon_usd/__init__.py
  client/ayon_usd/addon.py
  client/ayon_usd/hooks/usd_pinning_root.py
  client/ayon_usd/plugins/publish/extract_skeleton_pinning_json.py
  client/ayon_usd/plugins/publish/integrate_pinning_file.py
  client/ayon_usd/standalone/usd/pinning/_pinning_file_generation_funcs.py
  client/ayon_usd/utils.py
Labels: type: enhancement

#50 Fix execution condition and anatomy
  client/ayon_usd/hooks/usd_pinning_root.py
Labels: type: bug

#51 Add compatible addon
  package.py
Labels: type: enhancement
